import { Header } from "./component/header"

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">

      <body>
        <Header />
        {children}
        <footer style={{ padding: "1rem", backgroundColor: "ghostwhite" }}>
          <p>Footer</p>
        </footer>
      </body>
    </html>
  )
}
