export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function AuthLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <>
      <header style={{ backgroundColor: 'lightblue', padding: '1rem' }}>
        <h1>Auth Page!!</h1>
      </header>
      {children}
    </>
  )
}
