import { Header } from "../component/header";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function AfterLoginLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <>
      <Header />
      {children}
      <footer style={{ padding: "1rem", backgroundColor: "ghostwhite" }}>
        <p>Footer</p>
      </footer>
    </>
  );
}
